### ISSUE TITLE
Dow Jones Industrial Average Blank

### ISSUE THREAD

**Issue by ghost** [sirech/stock-display#3]
Currently not displaying Dow Jones (DJI) updates.  It shows as blank or no change for the past few days.  Thanks.

**Comment by sirech** [comment]
Yahoo is somehow not serving it anymore. I'll try to add another source for the info, but this is kind of a mayor change, so it will take some time

**Comment by ghost** [comment]
Yeah, I kind of figured it was something like that.  Good program, otherwise.

**Comment by sirech** [comment]
I found a workaround without having to change APIs. It is now working again

**Comment by ghost** [comment]
That did it.  Good job!  Thanks.
